"""Probe suites — the questions a night's adapter has to answer closed-book.

Suites in play:
  qaext_closed        per-day recall. The decay matrix is built from these.
  traps_closed        events that never happened. Calibration, not recall.
  heldout_days_closed days deliberately never trained on. A contamination
                      tripwire: if these rise, something leaked and the recall
                      numbers mean nothing.

The one rule with teeth: THE PROBE GENERATOR MUST NOT BE THE CORPUS GENERATOR.
If the same model writes the training prose and the questions about it, a high
score can mean "the two agree", which is not memory. Amplification is done by the
base-model family; probes come from the description pass. They must stay apart.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

QA_SUITE = "qaext_closed"
TRAPS_SUITE = "traps_closed"
HELDOUT_SUITE = "heldout_days_closed"


@dataclass(frozen=True)
class Probe:
    probe_id: str
    question: str
    gold: str
    scoring: str = "f1"
    day: int | None = None
    meta: dict[str, Any] = field(default_factory=dict)


class ProbeContamination(RuntimeError):
    """The probe set and the training corpus share a generator."""


def load_suite(probes_dir: str | Path, suite: str) -> list[Probe]:
    """Read `probes_<suite>.jsonl` + its `.gold.jsonl` sidecar, zipped by line.

    The two files are positionally paired, so a count mismatch means one of them
    was regenerated alone — every gold would then be attached to the wrong
    question and the eval would report confident nonsense."""
    root = Path(probes_dir)
    questions_path = root / f"probes_{suite}.jsonl"
    gold_path = root / f"probes_{suite}.gold.jsonl"
    if not (questions_path.exists() and gold_path.exists()):
        return []
    questions = [json.loads(line) for line in questions_path.read_text().splitlines() if line.strip()]
    golds = [json.loads(line) for line in gold_path.read_text().splitlines() if line.strip()]
    if len(questions) != len(golds):
        raise ValueError(f"{suite}: {len(questions)} probes vs {len(golds)} golds — "
                         "the pairing is positional, so this suite is unusable")
    probes = []
    for question, gold in zip(questions, golds):
        day = gold.get("day")
        probes.append(Probe(
            probe_id=str(gold.get("probe_id", "")),
            question=question["messages"][-1]["content"],
            gold=str(gold.get("gold", "")),
            scoring=str(gold.get("scoring", "f1")),
            day=int(day) if day is not None else None,
            meta={k: v for k, v in gold.items()
                  if k not in ("probe_id", "gold", "scoring", "day")}))
    return probes


def day_pool(probes: list[Probe], day: int, limit: int) -> list[Probe]:
    """The fixed, deterministic probe pool for one day.

    Same probes every step, so a cell of the decay matrix is comparable to the
    cell above it — a resampled pool would make forgetting indistinguishable from
    having drawn harder questions."""
    return [p for p in probes if p.day == day][:limit]


_FAMILY = re.compile(r"(gemini|gpt|claude|qwen|llama|mistral|deepseek)", re.I)


def generator_family(model_id: str) -> str:
    """'vertex_ai/gemini-2.5-flash' -> 'gemini'. Family, not exact id: two
    checkpoints of one family share priors and phrasings, so agreement between
    them is no more evidence of memory than self-agreement."""
    match = _FAMILY.search(model_id or "")
    return match.group(1).lower() if match else (model_id or "").strip().lower()


def assert_independent_generators(*, probe_generator: str | None,
                                  corpus_generator: str) -> None:
    """Enforce probe != corpus generator. Unknown provenance fails CLOSED."""
    if not probe_generator:
        raise ProbeContamination(
            "probe-set generator is unknown — cannot certify it differs from the "
            f"corpus generator {corpus_generator!r}; record provenance with the probes")
    if generator_family(probe_generator) == generator_family(corpus_generator):
        raise ProbeContamination(
            f"probes were generated by {probe_generator!r} and the training corpus by "
            f"{corpus_generator!r} — same family. A score from this pairing measures "
            "generator agreement, not what the weights hold.")
